import { AlertOctagon, ScanSearch, UserMinus } from "lucide-react";
import { SlideShell, SlideTitle, StatBlock, PullQuote } from "@/components/slide";
import { Card } from "@/components/ui/card";

export const DetectorBiasScreen = () => {
  return (
    <SlideShell tone="rose" ariaLabel="The AI detector bias crisis">
      <div className="space-y-10">
        <SlideTitle kicker="Chapter 06 · Academic integrity, revisited">
          The detector is the cheater.
        </SlideTitle>

        <div className="grid md:grid-cols-3 gap-6">
          <StatBlock
            value="61%"
            label="false-positive rate"
            note="Seven commercial detectors flagging TOEFL essays by non-native English writers as AI"
            icon={ScanSearch}
            accent="destructive"
          />
          <StatBlock
            value="97.8%"
            label="of those essays"
            note="were flagged as AI-generated by at least one detector"
            icon={AlertOctagon}
            accent="destructive"
          />
          <StatBlock
            value="100%"
            label='"AI-written"'
            note='An autistic student flagged at 100% — for "writing in the same formulaic manner as AI"'
            icon={UserMinus}
            accent="accent"
          />
        </div>

        <Card className="p-8 md:p-10 border-l-8 border-l-destructive bg-card/80 space-y-3">
          <p className="text-2xl md:text-3xl font-semibold text-foreground leading-snug">
            Autistic writing — direct, repetitive, structurally consistent —
            looks like AI to a detector.
          </p>
          <p className="text-xl md:text-2xl text-muted-foreground leading-snug">
            So does ESL writing. So does dyslexic writing assisted by spellcheck.
            <br />
            The students most likely to be flagged are the students least able to fight back.
          </p>
        </Card>

        <PullQuote variant="primary" attribution="Liang et al., Patterns 2023 · Bloomberg, 2024">
          Punishing students for sounding like AI
          <br />
          <span className="text-primary">punishes neurodivergence.</span>
        </PullQuote>
      </div>
    </SlideShell>
  );
};